server:
  port: 8090

spring:
  datasource:
    name: mysql
    url: jdbc:mysql://127.0.0.1:3306/mysql?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show-sql: true
        hbm2ddl:
          auto: none
          dialect: com.example.myview.config.MysqlConfig
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  mvc:
    favicon:
      enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.myview.entity